spring.application.name=ToDoApp
server.port = 9000
server.profiles.app=Production
server.error.include-stacktrace=ALWAYS
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5434/to-do-app
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.jpa.show-sql=true